version: '3'
services:
  db:
    image: postgres:12.4
    container_name: underline-db
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - .:/code

  underline:
    build:
      context: .
      dockerfile: ./docker/Docker.server/Dockerfile
    image: underline
    env_file: .env
    container_name: underline
    user: ${CURRENT_UID}
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db:postgres
  redis:
      image: redis
      container_name: underline-redis
      restart: on-failure
  
  celery:
      image: 'underline:latest'    
      command: celery -A underline worker -B -l INFO
      container_name: underline-celery
      volumes:
        - .:/code
      environment:
        - DJANGO_SETTINGS_MODULE=underline.settings
      env_file: .env
      depends_on:
        - redis
        - db
        - underline
      restart: on-failure
