# Generated by Django 3.1.6 on 2021-02-04 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_position_acronym'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='image_url',
            new_name='logo_url',
        ),
    ]
