# Generated by Django 3.1.6 on 2021-02-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210218_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pick',
            old_name='over_nba_points',
            new_name='under_nba_points',
        ),
        migrations.AlterField(
            model_name='pick',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
