# Generated by Django 3.1.6 on 2021-02-04 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210204_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='league',
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.position'),
            preserve_default=False,
        ),
    ]
