# Generated by Django 3.1.6 on 2021-02-08 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210206_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentdate',
            options={'verbose_name': 'Change the current date', 'verbose_name_plural': 'Change the current date'},
        ),
        migrations.RemoveField(
            model_name='playersforadate',
            name='points_over',
        ),
        migrations.RemoveField(
            model_name='playersforadate',
            name='premier',
        ),
        migrations.AddField(
            model_name='player',
            name='premier',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='core.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.league')),
            ],
        ),
    ]
