# Generated by Django 3.1.6 on 2021-02-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210204_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='headshot_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
