# Generated by Django 3.1.6 on 2021-02-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='order_data',
            new_name='order_details',
        ),
    ]
