# Generated by Django 3.1.6 on 2021-03-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210226_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentdate',
            options={'verbose_name': 'System date', 'verbose_name_plural': 'System date'},
        ),
        migrations.AddField(
            model_name='line',
            name='invalidated',
            field=models.BooleanField(default=False),
        ),
    ]
