# Generated by Django 3.1.6 on 2021-03-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210301_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='free_to_play',
            field=models.BooleanField(default=False),
        ),
    ]
