# Generated by Django 3.1.6 on 2021-05-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210309_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='slip',
            name='creator_slip',
            field=models.BooleanField(default=False),
        ),
    ]
