# Generated by Django 3.1.6 on 2021-06-02 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210602_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='nba_points_actual',
            new_name='actual_value',
        ),
        migrations.RenameField(
            model_name='pick',
            old_name='under_nba_points',
            new_name='under',
        ),
        migrations.RenameField(
            model_name='subline',
            old_name='nba_points_line',
            new_name='projected_value',
        ),
        migrations.AddField(
            model_name='line',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.linecategory'),
            preserve_default=False,
        ),
    ]
