# Generated by Django 3.1.6 on 2021-06-09 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210609_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='swing',
        ),
        migrations.CreateModel(
            name='SubMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swing', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.linecategory')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movement')),
            ],
        ),
    ]
