# Generated by Django 3.1.6 on 2021-06-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210609_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='submovement',
            name='minimum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
