# Generated by Django 3.1.6 on 2021-06-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_movement_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='line',
        ),
    ]
