# Generated by Django 3.1.6 on 2021-06-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_movement_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subline',
            name='movement',
        ),
        migrations.AddField(
            model_name='subline',
            name='submovement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.submovement'),
        ),
    ]
