# Generated by Django 3.1.6 on 2021-03-03 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_free_to_play'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='free_to_play',
        ),
    ]
