# Generated by Django 3.1.6 on 2021-03-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_free_to_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_to_play',
            field=models.BooleanField(default=False),
        ),
    ]
