# Generated by Django 3.1.6 on 2021-05-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_free_to_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='handle',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
