# Generated by Django 3.1.6 on 2021-05-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_handle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='handle',
            new_name='username',
        ),
    ]
