# Generated by Django 3.1.6 on 2021-06-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_current_creator_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creator',
            field=models.BooleanField(default=False),
        ),
    ]
