# Generated by Django 3.1.6 on 2021-06-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_creator_slip',
        ),
    ]
